import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider as CustomThemeProvider } from "@/context/theme-context";
import { ThemeProvider as NextThemesProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={inter.className}>
        <NextThemesProvider attribute="class" defaultTheme="system">
          <CustomThemeProvider>
            {children}
          </CustomThemeProvider>
        </NextThemesProvider>
      </body>
    </html>
  );
}
