version: "3.9"

services:
  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    
  tests:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ["python", "-m", "unittest", "discover", "-s", "tests"]