version: "3.9"

services:
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    networks:
      - app-network

  test-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.test
    networks:
      - app-network
    command: ["npm", "run", "test"]
    environment:
      - NODE_ENV=test

  test-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - app-network
    command: ["python", "tests/run_tests.py"]
    environment:
      - LOG_LEVEL=ERROR
    logging:
      driver: "none"

networks:
  app-network:
    driver: bridge
